
services:
  ros-noetic:
    build:
      context: .
    container_name: ros_noetic
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./catkin_ws:/root/catkin_ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /usr/local/cuda:/usr/local/cuda
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "source /opt/ros/noetic/setup.bash &&
               cd /root/catkin_ws &&
               catkin_make &&
               exec bash"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    privileged: true
    network_mode: host
    tty: true
